//
//  Strings.m
//  Airbitz
//
//  Created by Paul P on 1/3/16.
//  Copyright © 2016 Airbitz. All rights reserved.
//

#define backButtonText                              NSLocalizedString(@"Back", @"Back button text on top left")
#define exitButtonText                              NSLocalizedString(@"Exit", @"Exit button text on top left")
#define helpButtonText                              NSLocalizedString(@"Help", @"Help button text on top right")
#define infoButtonText                              NSLocalizedString(@"Info", @"Info button text on top right")
#define doneButtonText                              NSLocalizedString(@"Done", @"Generic DONE button text")
#define cancelButtonText                            NSLocalizedString(@"CANCEL", @"Generic CANCEL button text")
#define goBackButtonText                            NSLocalizedString(@"Go Back", @"Generic Go Back button text")
#define closeButtonText                             NSLocalizedString(@"Close", @"Generic CLOSE button text")
#define shareButtonText                             NSLocalizedString(@"Share", @"Generic SHARE button text")
#define exportButtonText                            NSLocalizedString(@"Export", @"EXPORT button text for wallet export")
#define renameButtonText                            NSLocalizedString(@"Rename", @"RENAME button text for wallet rename")
#define deleteButtonText                            NSLocalizedString(@"Delete", @"DELETE button text for wallet delete")
#define disable_text                                NSLocalizedString(@"Disable", @"Disable as in to disable a feature")
#define okButtonText                                NSLocalizedString(@"OK", @"OK button text")
#define send_button_text                            NSLocalizedString(@"SEND", @"SEND button text")
#define copyButtonText                              NSLocalizedString(@"Copy", @"Copy button text")
#define skipButtonText                              NSLocalizedString(@"Skip", @"Skip button text")
#define nextButtonText                              NSLocalizedString(@"Next", @"Next button text")
#define laterButtonText                             NSLocalizedString(@"Later", @"Later button text")
#define noButtonText                                NSLocalizedString(@"NO", @"NO button text")
#define yesButtonText                               NSLocalizedString(@"YES", @"YES button text")
#define loginButtonText                             NSLocalizedString(@"LOGIN", @"LOGIN button text")
#define approve_button_text                         NSLocalizedString(@"Approve", @"APPROVE button text")
#define accept_button_text                          NSLocalizedString(@"Accept", @"ACCEPT button text")
#define loginButtonText                             NSLocalizedString(@"LOGIN", @"LOGIN button text")
#define changeButtonText                            NSLocalizedString(@"CHANGE", @"CHANGE button text")
#define checkPasswordButtonText                     NSLocalizedString(@"Check Password", @"Check password button text")
#define walletBalanceHeaderText                     NSLocalizedString(@"TOTAL: ", @"Prefix of wallet balance dropdown header")
#define walletNameHeaderText                        NSLocalizedString(@"Wallet: ", @"Prefix of wallet name on rename popup")
#define renameWalletWarningText                     NSLocalizedString(@"Wallet name must have at least one character", nil)
#define transactionCellNoTransactionsText           NSLocalizedString(@"No Transactions", @"what to display when wallet has no transactions")
#define transactionCellNoTransactionsFoundText      NSLocalizedString(@"No Transactions Found", @"what to display when no transactions are found in search")
#define fiatText                                    NSLocalizedString(@"Fiat", @"Fiat")
#define walletHeaderButtonHelpText                  NSLocalizedString(@"To sort wallets, tap and drag the 3 bars to the right of a wallet. Drag below the [ARCHIVE] header to archive the wallet", @"Popup wallet help test")
#define walletHasBeenArchivedText                   NSLocalizedString(@"This wallet has been archived. Please select a different wallet from the [Wallets] screen", @"Popup sessage for when a wallet is archived")
#define walletsPopupHelpText                        NSLocalizedString(@"Tap and hold a wallet for additional options", nil)
#define selectWalletTransferPopupHeaderText         NSLocalizedString(@"▼ Choose a wallet to transfer funds to ▼", @"Header of popup in SendView from wallet to wallet transfer")
#define invalidAddressPopupText                     NSLocalizedString(@"Invalid Bitcoin Address", nil)
#define invalidQRCode                               NSLocalizedString(@"Invalid QR Code", nil)
#define enterBitcoinAddressPopupText                NSLocalizedString(@"Send to Bitcoin Address or Import Private Key", nil)
#define deleteAccountText                           NSLocalizedString(@"Delete Account", nil)
#define deleteAccountWarning                        NSLocalizedString(@"Delete '%@' on this device? This will disable access via PIN. If 2FA is enabled on this account, this device will not be able to login without a 2FA reset which takes 7 days.", @"Delete Account Warning")
#define deleteAccountNoPasswordWarningText          NSLocalizedString(@"Delete '%@' on this device? This account has no password and will NOT BE RECOVERABLE if you delete it.", @"Delete Account With no Password Warning")
#define enterBitcoinAddressPlaceholder              NSLocalizedString(@"Bitcoin Address or Private Key", nil)
#define enterPrivateKeyPopupText                    NSLocalizedString(@"Sweep Funds From Private Key", nil)
#define enterPrivateKeyPlaceholder                  NSLocalizedString(@"Bitcoin Private Key", nil)
#define smsText                                     NSLocalizedString(@"SMS", @"text for textmessage/SMS")
#define emailText                                   NSLocalizedString(@"Email", @"text for Email")
#define sendScreenHelpText                          NSLocalizedString(@"Scan the QR code of payee to send payment or tap on a bluetooth request from the list below", nil)
#define creatingWalletText                          NSLocalizedString(@"Creating and securing wallet", nil)
#define createAccountAndTransferFundsText           NSLocalizedString(@"Please create a new account and transfer your funds if you forgot your password.", nil)
#define createPasswordForAccountText                NSLocalizedString(@"Please create a password for this account or you will not be able to recover your account if your device is lost or stolen.", nil)
#define settingsText                                NSLocalizedString(@"Settings", nil)
#define categoriesText                              NSLocalizedString(@"Categories", nil)
#define signupText                                  NSLocalizedString(@"Sign Up", nil)
#define changePasswordText                          NSLocalizedString(@"Change Password", nil)
#define changePINText                               NSLocalizedString(@"Change PIN", nil)
#define twoFactorText                               NSLocalizedString(@"Two Factor", nil)
#define importText                                  NSLocalizedString(@"Import", nil)
#define buySellText                                 NSLocalizedString(@"Buy/Sell Bitcoin", nil)
#define spend_bitcoin_plugin_text                   NSLocalizedString(@"Spend Bitcoin (Plugins)", nil)
#define plugin_popup_notice                         NSLocalizedString(@"The following services are not provided by %@.\n\nFor issues and feedback, please contact the respective service providers.",nil)

#define passwordRecoveryText                        NSLocalizedString(@"Password Recovery", nil)
#define passwordMismatchText                        NSLocalizedString(@"Password does not match. Re-enter password", @"")
#define defaultCurrencyInfoText                     NSLocalizedString(@"Note: Default Currency setting is only used for new wallets and to show total balance of account. Create a new wallet to change the fiat currency shown in each transaction.", nil)
#define touchIDPromptText                           NSLocalizedString(@"Touch to login user", @"Touch ID prompt text")
#define usePINText                                  NSLocalizedString(@"Use PIN", @"Touch ID [Use PIN] button")
#define usePasswordText                             NSLocalizedString(@"Use Password", @"Touch ID [Use Password] button")
#define twofactorWarningText                        NSLocalizedString(@"Two Factor Enabled\n\n** Warning **\n\nIf you lose your device or uninstall the app, it will take 7 days to disable 2FA and access your account.\"", @"2FA warning on enable")
#define loadingAccountText                          NSLocalizedString(@"Loading Account...", @"Loading account alert text")
#define loadingWalletsText                          NSLocalizedString(@"Loading Wallets...", @"Loading wallets alert text")
#define fetchingPaymentRequestText                  NSLocalizedString(@"Fetching Payment Request...", @"Fetching Payment Request popup")
#define loadingWalletsNewDeviceText                 NSLocalizedString(@"This may take a few minutes if it is the first time logging into this device.", @"Loading Wallets alert text")
#define loadingTransactionsText                     NSLocalizedString(@"Loading Transactions...", @"Loading Transactions alert text")
#define synchronizingText                           NSLocalizedString(@"Synchronizing", @"Synchronizing text in confirmation textfield")
#define pendingText                                 NSLocalizedString(@"Pending", @"Pending status in transaction list")
#define warningRBFText                              NSLocalizedString(@"Warning: Replace by Fee Detected. Double spend likely", @"RBF status in transaction list")
#define doubleSpendText                             NSLocalizedString(@"Warning: Double Spend", @"Double spend status in transaction list")
#define confirmationText                            NSLocalizedString(@"Confirmation", @"Num of confirmations in transaction list")
#define confirmationsText                           NSLocalizedString(@"Confirmations", @"Num of confirmations in transaction list")
#define confirmedText                               NSLocalizedString(@"Confirmed", @"Confirmed status in transaction list")
#define loadingText                                 NSLocalizedString(@"Loading...", @"Loading...")
#define showBalanceText                             NSLocalizedString(@"Show Balance", nil)
#define uploadLogFileText                           NSLocalizedString(@"Upload Log File", nil)
#define enterAnyNotesForSupportStaff                NSLocalizedString(@"Enter any notes you would like to send to our support staff", nil)
#define uploadLogText                               NSLocalizedString(@"Upload Log", nil)
#define emailLoginPackage                           NSLocalizedString(@"Email Login Package", nil)
#define uploadingLogText                            NSLocalizedString(@"Uploading logfile. Please wait...", @"Uploading logfile fading popup")
#define uploadSuccessfulText                        NSLocalizedString(@"Upload Successful", @"Upload Successful fading popup")
#define uploadFailedText                            NSLocalizedString(@"Upload Failed. Please check your network connection", @"Upload Failed")
#define watcherClearedText                          NSLocalizedString(@"Watcher Database Cleared. Please allow a few minutes to resync blockchain info. Transactions and balances may be inaccurate during sync", @"Watcher Database Cleared popup text")
#define watcherClearedWithErrorText                 NSLocalizedString(@"Watcher Database Cleared But Error Occurred. Please allow a few minutes to resync blockchain info. Transactions and balances may be inaccurate during sync", @"Watcher Database Cleared popup text")
#define PINOnlyNumbersText                          NSLocalizedString(@"Only numbers allowed in PIN", @"")
#define scanQrToSendFundsText                       NSLocalizedString(@"Scan QR to Send, Import, or Login with BitID", @"Text at top of Send screen")
#define scanQrToImportPrivateKeyOrGiftCard          NSLocalizedString(@"Scan QR to Import Private Key/Gift Card", @"Text at top of Scan Screen")
#define signupUsernameText                          NSLocalizedString(@"This is not your email or real name.\n\nThis is the username to login into your [[abtag APP_TITLE]] account on this and other devices.\n\nYour username and password are known only to you and never stored unencrypted.", "Username Signup screen info text")
#define signupCameraText                            NSLocalizedString(@"You will next see a popup requesting access to your Camera.\n\n[[abtag APP_TITLE]] needs this to scan QR codes to pay people and merchants.",@"Camera signup screen")
#define signupContactsText                          NSLocalizedString(@"[[abtag APP_TITLE]] uses contacts to help tag information regarding your transactions.\n\nAll tagged information is kept 100% private and encrypted by your password.\n\nNo one, including [[abtag APP_TITLE]], has any access to this information.",@"Contacts signup screen")
#define importPrivateKeyText                        NSLocalizedString(@"IMPORT PRIVATE KEY\n([[abtag APP_TITLE]] Gift Card)", @"Slideout menu import private key text")
#define spend_bitcoin_text_label                    NSLocalizedString(@"SPEND BITCOIN (Plugins)", @"Slideout menu spend text")
#define bitcoinWalletTransactionsText               NSLocalizedString(@"Bitcoin Wallet Transactions", @"Export wallet transactions email subject line")
#define accountsNeedsPasswordNotificationTitle      NSLocalizedString(@"WARNING: missing password", @"Title of missing password notification")
#define accountsNeedsPasswordNotificationMessage    NSLocalizedString(@"Account '%@' needs a password. Account is not accessible on a new device without a password.", nil)
#define renameWalletText                            NSLocalizedString(@"Rename Wallet", @"Rename Wallet popup")
#define deleteWalletText                            NSLocalizedString(@"Delete Wallet", @"Delete Wallet popup")
#define deleteWalletWarningText                     NSLocalizedString(@"Are you sure? You will be unable to access any funds in this wallet and any future funds that it may receive", nil)
#define deleteWalletHasFunds                        NSLocalizedString(@"Cannot delete wallet as it contains funds. Please transfer out funds first.",nil)
#define deletingWalletText                          NSLocalizedString(@"Deleting Wallet", @"Text for popup while deleting wallet")
#define deleteWalletErrorText                       NSLocalizedString(@"Error Deleting Wallet",nil)
#define deleteWalletDeletedText                     NSLocalizedString(@"Wallet Deleted",nil)
#define rememberYourPasswordText                    NSLocalizedString(@"Remember your password?", nil)
#define rememberYourPasswordWarningText             NSLocalizedString(@"Do you still remember your password? You will need your password if your device gets lost or stolen, or if you uninstall the app.\nEnter it below to make sure:", nil)
#define greatJobRememberingPasswordText             NSLocalizedString(@"Great job remembering your password.", nil)
#define incorrectPasswordText                       NSLocalizedString(@"Incorrect Password", nil)
#define incorrectPasswordTryAgainText               NSLocalizedString(@"Incorrect Password. Try again, or change it now?", nil)
#define howAreYouLikingAirbitzText                  NSLocalizedString(@"How are you liking %@?", @"Like Airbitz popup")
#define notSoGoodText                               NSLocalizedString(@"Not so good", nil)
#define itsGreatText                                NSLocalizedString(@"It's great", nil)
#define receivedFundsText                           NSLocalizedString(@"Received Funds", nil)
#define bitcoinReceivedTapText                      NSLocalizedString(@"%@ Bitcoin received. Tap for details.", nil)
#define youReceivedBitcoinText                      NSLocalizedString(@"You Received Bitcoin!\n%@ (~%@)", nil)
#define youReceivedBitcoinUsePayeeText              NSLocalizedString(@"You received Bitcoin!\n%@ (~%@)\nUse the Payee, Category, and Notes field to optionally tag your transaction", nil)
#define wouldYouLikeToSendFeedbackText              NSLocalizedString(@"Would you like to send us some feedback?", nil)
#define noThanksText                                NSLocalizedString(@"No thanks", nil)
#define wouldYouLikeToWriteReviewText               NSLocalizedString(@"Would you like to write a review in the App store?", nil)
#define cantSendEmailText                           NSLocalizedString(@"Can't send e-mail",nil)
#define enter_username_in_login_screen              NSLocalizedString(@"Please enter a username at the login screen",nil)
#define navbarToWalletPrefixText                    NSLocalizedString(@"To: %@ ▼", "Top of screen wallet dropdown prefix text")
#define setPasswordAndPinText                       NSLocalizedString(@"Set a Password and PIN",nil)
#define setPasswordText                             NSLocalizedString(@"Set a Password",nil)
#define warningWithoutPasswordTitleText             NSLocalizedString(@"Account has no password",nil)
#define warningWithoutPasswordPopupText             NSLocalizedString(@"Warning. Without a password, you will not be able to login on a new device if this device is lost or stolen, or if this app is uninstalled", nil)
#define errorRecoveringAccountTitle                 NSLocalizedString(@"Error Recovering Account",nil)
#define errorRecoveringAccountText                  NSLocalizedString(@"Please try again later or contact support",nil)
#define setRecoveryQuestionsFailed                  NSLocalizedString(@"Setting recovery questions failed:\n%@", nil)
#define error_disabling_recovery                    NSLocalizedString(@"Error disabling recovery",nil)
#define recovery_disabled                           NSLocalizedString(@"Recovery Disabled",nil)
#define recoveryQuestionsNotSet                     NSLocalizedString(@"Recovery Questions Not Set", @"Title of recovery questions setup error alert")
#define recoveryQuestionsSet                        NSLocalizedString(@"Recovery Questions Set", @"Title of recovery questions setup complete alert")
#define recoveryQuestionsSetWarning                 NSLocalizedString(@"Your password recovery questions and answers are now set up.  When recovering your password, your answers must match exactly. **DO NOT FORGET YOUR PASSWORD AND RECOVERY ANSWERS** YOUR ACCOUNT CANNOT BE RECOVERED WITHOUT THEM!!",nil)
#define defaultWalletName                           NSLocalizedString(@"My Wallet", @"Default wallet name for new accounts")
#define errorGettingWalletCount                     NSLocalizedString(@"Error Getting Wallet Count", nil)
#define generatingQRCode                            NSLocalizedString(@"Generating QR Code...", nil)
#define imagePickerAlertTitle                       NSLocalizedString(@"Upload Image", nil)
#define imagePickerAlertUseCamera                   NSLocalizedString(@"Use Camera", nil)
#define imagePickerAlertUsePhotos                   NSLocalizedString(@"Use Photo Album", nil)
#define yourPasswordText                            NSLocalizedString(@"Your password...", @"Start of password rules text")
#define mustHaveUpperCase                           NSLocalizedString(@"Must have at least one upper case letter",nil)
#define mustHaveLowerCase                           NSLocalizedString(@"Must have at least one lower case letter",nil)
#define mustHaveNumber                              NSLocalizedString(@"Must have at least one number",nil)
#define mustHaveMoreCharacters                      NSLocalizedString(@"Must have at least %d characters",nil)
#define bitcoinPrivateKeyText                       NSLocalizedString(@"Bitcoin Private Key with Public Address", nil)
#define bitIDLogin                                  NSLocalizedString(@"BitID Login", nil)
#define bitIDIdentity                               NSLocalizedString(@"BitID Identity", nil)
#define edge_login                                  NSLocalizedString(@"Edge Login", nil)
#define wouldYouLikeToSendOrImport                  NSLocalizedString(@"Would you like to send funds to this address or import funds into your wallet?", nil)
#define importFunds                                 NSLocalizedString(@"Import Funds",nil)
#define sendFundsToPrivateKey                       NSLocalizedString(@"Send Funds to Private Key",nil)
#define balanceButtonText                           NSLocalizedString(@"Balance", nil)
#define transferToWalletText                        NSLocalizedString(@"Transfer To %@", @"To wallet transfer text")
#define transferFromWalletText                      NSLocalizedString(@"Transfer From %@", @"From wallet transfer text")
#define notesAffiliateRevenue                       NSLocalizedString(@"Revenue share from affiliate link %@", @"Income notes field for affiliate revenue")
#define debugButtonText                             NSLocalizedString(@"Debug", @"debug text")
#define getAffiliateLinkButtonText                  NSLocalizedString(@"Get Affiliate Link", @"Button text for Get Affiliate Link")
#define requestIsCopiedToClipboardText              NSLocalizedString(@"Request is copied to the clipboard", nil)
#define affiliateLinkIsCopiedToClipboardText        NSLocalizedString(@"Affiliate link has been copied to the clipboard", nil)
#define shareThisLinkAndReceiveRevenue              NSLocalizedString(@"%@\n\nShare this link to receive revenue from users that install and use %@. You will receive 0.25%% of all gift card purchases made inside of this app.", nil)
#define affiliateLinkShareText                      NSLocalizedString(@"Download the Airbitz wallet and save money using bitcoin", nil)
#define messageSentText                             NSLocalizedString(@"Message Sent", nil)
#define answersAreCaseSensitiveText                 NSLocalizedString(@"Answers are case sensitive", @"Warning for password recovery textfields")
#define autoLogoffAfterText                         NSLocalizedString(@"Auto log off after", @"settings text")
#define buyBitcoinButton                            NSLocalizedString(@"Buy Bitcoin",nil)
#define importAirbitzGiftCardButton                 NSLocalizedString(@"Import Airbitz Gift Card",nil)
#define upTo20OffStarbucksButton                    NSLocalizedString(@"Up to 20% off Starbucks",nil)
#define upTo10OffTargetButton                       NSLocalizedString(@"Up to 10% off Target",nil)
#define upTo15to20OffAmazonButton                   NSLocalizedString(@"15-20% off Amazon",nil)
#define mobile_phone_topups                         NSLocalizedString(@"Top Up Prepaid Phones", nil)
#define starbucks_20_percent_off                    NSLocalizedString(@"Starbucks (Up to 20% Off)", nil)
#define target_10_percent_off                       NSLocalizedString(@"Target (Up to 10% Off)", nil)
#define homedepot_15_percent_off                    NSLocalizedString(@"Home Depot (Up to 15% Off)", nil)
#define walmart_10_percent_off                      NSLocalizedString(@"Walmart (Up to 10% Off)", nil)
#define wholefoods_10_percent_off                   NSLocalizedString(@"Whole Foods (Up to 10% Off)", nil)
#define importPrivateKeyButton                      NSLocalizedString(@"Import Private Key", nil)
#define debugOptionsTitle                           NSLocalizedString(@"Debug Options", @"Debug screen header title")
#define restartingWatcherServiceText                NSLocalizedString(@"Restarting watcher service", nil)
#define noPasswordSetText                           NSLocalizedString(@"No password set", nil)
#define passwordChangeText                          NSLocalizedString(@"Password Change", nil)
#define passwordToAccountChangeText                 NSLocalizedString(@"The password to this account was changed by another device. Please login using the new credentials.", nil)
#define tfaOnText                                   NSLocalizedString(@"Two Factor Authentication On", nil)
#define tfaEnabledFromDifferentDeviceText           NSLocalizedString(@"Two Factor Authentication (enchanced security) has been enabled from a different device for this account. Please enable 2 Factor Authentication for full access from this device.", nil)
#define remindMeLaterText                           NSLocalizedString(@"Remind Me Later", nil)
#define enableButtonText                            NSLocalizedString(@"Enable", nil)
#define tfaInvalidText                              NSLocalizedString(@"Two Factor Invalid", nil)
#define tfaTokenOnThisDeviceInvalidText             NSLocalizedString(@"The Two Factor Authentication token on this device is invalid. Either the token was changed by a different device our your clock is skewed. Please check your system time to ensure it is correct.", nil)
#define checkingPasswordText                        NSLocalizedString(@"Checking password...", nil)
#define sentBitcoinText                             NSLocalizedString(@"Sent Bitcoin", nil)
#define receivedBitcoinText                         NSLocalizedString(@"Received Bitcoin", nil)
#define referYourFriendsText                        NSLocalizedString(@"Refer Your Friends", nil)
#define referYourFriendsAndGetRevenue               NSLocalizedString(@"REFER YOUR FRIENDS\n(Earn Bitcoin)", nil)
#define importFailedPrivateKeyEmpty                 NSLocalizedString(@"Import failed. Private key is empty", nil)
#define importFailedText                            NSLocalizedString(@"Import failed", nil)
#define errorCodeText                               NSLocalizedString(@"Error code", nil)
#define errorDescriptionText                        NSLocalizedString(@"Error desc", nil)
#define appnameHasRequestedABitcoinAddress          NSLocalizedString(@"%@ has requested a bitcoin address to send money to.", nil)
#define anAppHasRequestedABitcoinAddress            NSLocalizedString(@"An app has requested a bitcoin address to send money to.", nil)
#define pleaseChooseAWalletToReceiveFunds           NSLocalizedString(@" Please choose a wallet to receive funds.", nil)
#define areYouSureYouWantToCall                     NSLocalizedString(@"Are you sure you want to call", nil)
#define placeCallText                               NSLocalizedString(@"Place Call", nil)
#define addNewText                                  NSLocalizedString(@"Add New", nil)
#define areYouSureYouWantToCancel                   NSLocalizedString(@"Are you sure you want to cancel any changes you've made?", nil)
#define currentLocationString                       NSLocalizedString(@"Current Location", nil)
#define onTheWebString                              NSLocalizedString(@"On The Web", nil)
#define cityStateProvinceOrCountry                  NSLocalizedString(@"City, State/Province, or Country", @"City, State/Province, or Country placeholder")
#define directoryText                               NSLocalizedString(@"Directory", @"Directory title bar text")
#define restaurantsAndFoodTrucks                    NSLocalizedString(@"Restaurants & Food Trucks", nil)
#define coffeeAndTea                                NSLocalizedString(@"Coffee & Tea", nil)
#define giftCards                                   NSLocalizedString(@"Gift Cards", nil)
#define electronicsText                             NSLocalizedString(@"Electronics", nil)
#define shoppingText                                NSLocalizedString(@"Shopping", nil)
#define atmSearchString                             NSLocalizedString(@"ATM" ,nil)
#define restaurantsAndFoodTrucks_en                 @"Restaurants & Food Trucks"
#define coffeeAndTea_en                             @"Coffee & Tea"
#define giftCards_en                                @"Gift Cards"
#define electronicsText_en                          @"Electronics"
#define shoppingText_en                             @"Shopping"
#define atmSearchString_en                          @"ATM"
#define businessNameOrCategory                      NSLocalizedString(@"Business Name or Category", @"Business Name or Category placeholder")
#define searchText                                  NSLocalizedString(@"Search", @"SearchBarSearch placeholder")
#define walletExport                                NSLocalizedString(@"Wallet Export", nil)
#define privateSeedText                             NSLocalizedString(@"Private Seed", nil)
#define publicSeedText                              NSLocalizedString(@"Public Seed (XPub)", nil)
#define exportWalletTransactions                    NSLocalizedString(@"Export Wallet Transactions", nil)
#define airprintIsNotAvailable                      NSLocalizedString(@"AirPrint is not currently available", nil)
#define walletPrivateSeed                           NSLocalizedString(@"Wallet Private Seed", nil)
#define exportPrivateSeed                           NSLocalizedString(@"Export Private Seed", nil)
#define exportPublicSeed                            NSLocalizedString(@"Export Public Seed (XPub)", nil)
#define emailCancelled                              NSLocalizedString(@"Email cancelled.", nil)
#define emailSavedToSendLater                       NSLocalizedString(@"Email saved to send later.", nil)
#define emailSent                                   NSLocalizedString(@"Email sent.", nil)
#define errorSendingEmail                           NSLocalizedString(@"Error sending Email.", nil)
#define usernameText                                NSLocalizedString(@"Username", @"Username")
#define anErrorOccurredNetworkOrIncorrectPassword   NSLocalizedString(@"An error occurred. Possible network connection issue or incorrect username & password", nil)
#define pleaseEnterAUsername                        NSLocalizedString(@"Please enter a User Name", nil)
#define enableTouchIDText                           NSLocalizedString(@"Enable Touch ID", nil)
#define wouldYouLikeToEnableTouchID                 NSLocalizedString(@"Would you like to enable TouchID for this account and device?", nil)
#define pinLoginErrorText                           NSLocalizedString(@"An error occurred. Please check your network connection. You may also exit PIN login and use your username & password to login offline", nil)
#define touchIDDisabled                             NSLocalizedString(@"Touch ID Disabled", nil)
#define touchIDEnabledText                          NSLocalizedString(@"Touch ID Enabled", nil)
#define tryAgainText                                NSLocalizedString(@"Try again?", nil)
#define touchIDText                                 NSLocalizedString(@"Touch ID", nil)
#define enterYourPasswordToEnableTouchID            NSLocalizedString(@"Please enter your password to enable Touch ID", nil)
#define feedbackText                                NSLocalizedString(@"Feedback" ,nil)
#define loginPackage                                NSLocalizedString(@"Login Package", nil)
#define loggingOutText                              NSLocalizedString(@"Logging Out", nil)
#define moreCategoriesText                          NSLocalizedString(@"More Categories", @"")
#define twoFactorResetText                          NSLocalizedString(@"Two Factor Reset", nil)
#define aTwoFactorResetHasBeenRequested             NSLocalizedString(@"A two factor reset has been requested. If you did not create this request, login as %@ and change your password." ,nil)
#define warningExclamationText                      NSLocalizedString(@"Warning!", nil)
#define aboutToExitPasswordRecovery                 NSLocalizedString(@"You are about to exit password recovery setup. Your chosen questions and answers have not been saved.", nil)
#define skipThisStepText                            NSLocalizedString(@"Skip this step", @"Title of Skip this step alert")
#define warningYouWillNeverBeAbleToRecover          NSLocalizedString(@"**WARNING** You will NEVER be able to recover your password if it is forgotten!!", @"")
#define completeSignupText                          NSLocalizedString(@"Complete Signup", @"")
#define passwordRecoverySetup                       NSLocalizedString(@"Password Recovery Setup", @"")
#define wrongAnswersText                            NSLocalizedString(@"Wrong Answers", nil)
#define givenAnswersAreIncorrect                    NSLocalizedString(@"The given answers were incorrect. Please try again.", nil)
#define unableToImportToken                         NSLocalizedString(@"Unable to import token", nil)
#define errorImportingTokenTryAgain                 NSLocalizedString(@"Error importing the token at this time. Please try again.", nil)
#define passwordMismatchTitle                       NSLocalizedString(@"Password mismatch", nil)
#define pleaseEnterCorrectPassword                  NSLocalizedString(@"Please enter your correct password.", nil)
#define timeToCrackText                             NSLocalizedString(@"Time to crack:", @"text in password verification popup")
#define presentQRCodeToSender                       NSLocalizedString(@"Present QR code to Sender and have them scan to send you payment",nil)
#define errorOccurredCopyingToClipboard             NSLocalizedString(@"Error occured copying to the clipboard", nil)
#define waitingForPaymentText                       NSLocalizedString(@"Waiting for Payment...", @"Status on Request screen");
#define amountRequestedString                       NSLocalizedString(@"Requested...", @"Requested string on Request screen")
#define amountRemainingString                       NSLocalizedString(@"Remaining...", @"Remaining string on Request screen")
#define amountReceivedString                        NSLocalizedString(@"Received...", @"Received string on Request screen")
#define enterAmountOptionalText                     NSLocalizedString(@"Enter Amount (optional)", "Placeholder text for Receive screen amount")
#define connectedText                               NSLocalizedString(@"Connected", "Popup text when BLE connects")
#define warningWithAsterisks                        NSLocalizedString(@"** Warning **", @"** Warning ** text on partial payment")
#define partialPaymentText                          NSLocalizedString(@"Partial Payment", @"Text on partial payment")
#define paymentReceivedText                         NSLocalizedString(@"Payment received", @"Text on payment recived popup")
#define requestNotesFormatString                    NSLocalizedString(@"%@ / %@ requested via %@ on %@.", @"ie. $1.50 / 5 mB requested via email on Sep 16, 1976")
#define bitcoinRequestFormatString                  NSLocalizedString(@"%@ Bitcoin Request from %@" ,nil)
#define bitcoinRequestFromFormatString              NSLocalizedString(@"%@ Bitcoin Request" ,nil)
#define debugLogFileText                            NSLocalizedString(@"Debug Log File" ,nil)
#define qrCodeScanFailure                           NSLocalizedString(@"QR Code Scan Failure", nil)
#define unableToScanQR                              NSLocalizedString(@"Unable to scan QR code", nil)
#define bitcoinAddressMismatch                      NSLocalizedString(@"Bitcoin address mismatch", nil)
#define sorryText                                   NSLocalizedString(@"Sorry", nil)
#define congratulationsText                         NSLocalizedString(@"Congratulations", nil)
#define pingMustBeXXXDigitsFormatString             NSLocalizedString(@"PIN must be %d digits", @"")
#define accountSignUpText                           NSLocalizedString(@"Account Sign Up", @"Title of account signin error alert")
#define youMustEnterAUsername                       NSLocalizedString(@"You must enter a user name", @"")
#define usernameMustBeAtLeastXXXCharacters          NSLocalizedString(@"Username must be at least %d characters.", @"")
#define incorrectCurrentPassword                    NSLocalizedString(@"Incorrect current password", @"")
#define passwordSuccessfullyChanged                 NSLocalizedString(@"Password successfully changed. DO NOT FORGET YOUR PASSWORD OR RECOVERY ANSWERS! THEY CANNOT BE RECOVERED!", @"")
#define recoveryPasswordReminder                    NSLocalizedString(@"Recovery Password Reminder", nil)
#define receivedBitcoinRecommendSetupRecovery       NSLocalizedString(@"You've received Bitcoin! We STRONGLY recommend setting up Password Recovery questions and answers. Otherwise you will NOT be able to access your account if your password is forgotten.", nil)
#define youMustAnswerAllSix                         NSLocalizedString(@"You must answer all questions. Make sure your answers are long enough." ,nil)
#define youMustChooseAllSix                         NSLocalizedString(@"You must choose a question for all selections before proceeding." ,nil)
#define smsCancelledText                            NSLocalizedString(@"SMS cancelled" ,nil)
#define errorSendingSMS                             NSLocalizedString(@"Error sending SMS" ,nil)
#define smsSent                                     NSLocalizedString(@"SMS sent" ,nil)
#define bitcoinAddressMismatchFormatText            NSLocalizedString(@"The bitcoin address of the device you connected with:%@ does not match the address that was initially advertised:%@" ,nil)
#define pinOrPasswordCheckFailedFormatString        NSLocalizedString(@"%@ failed:\n%@" ,nil)
#define signupFailedFormatString                    NSLocalizedString(@"Sign-Up failed:\n%@" ,nil)
#define passwordChangeFailedFormatString            NSLocalizedString(@"Password change failed:\n%@" ,nil)
#define selectCurrencyText                          NSLocalizedString(@"Select Currency", nil)
#define sendingDotDotDot                            NSLocalizedString(@"Sending...", @"status message")
#define passwordText                                NSLocalizedString(@"Password", nil)
#define fourDigitPINText                            NSLocalizedString(@"4 Digit PIN", nil)
#define pleaseWait1SecondFormatString               NSLocalizedString(@"Please wait 1 second before retrying %@", nil)
#define pleaseWaitXXXSecondsFormatString            NSLocalizedString(@"Please wait %.0f seconds before retrying %@", nil)
#define pleaseEnterYourPIN                          NSLocalizedString(@"Please enter your PIN", nil)
#define incorrectPINPleaseWaitXXX                   NSLocalizedString(@"Incorrect PIN. Please wait %.0f seconds and try again.", nil)
#define incorrectPIN                                NSLocalizedString(@"Incorrect PIN", nil)
#define pleaseEnterAnAmountToSend                   NSLocalizedString(@"Please enter an amount to send", nil)
#define amountIsTooSmall                            NSLocalizedString(@"Amount is too small", nil)
#define errorDuringSend                             NSLocalizedString(@"Error during send", nil)
#define newPasswordText                             NSLocalizedString(@"New Password", @"")
#define reenterNewPasswordText                      NSLocalizedString(@"Re-enter New Password", @"")
#define currentPasswordText                         NSLocalizedString(@"Current Password", @"")
#define newPINText                                  NSLocalizedString(@"New PIN", @"")
#define insufficientPasswordText                    NSLocalizedString(@"Insufficient Password", @"Title of password check popup alert")
#define closedText                                  NSLocalizedString(@"closed",@"business listings is closed")
#define unableToUpdateSettings                      NSLocalizedString(@"Unable to update Settings", nil)
#define hideText                                    NSLocalizedString(@"Hide", "Hide")
#define showText                                    NSLocalizedString(@"Show", "Show")
#define enterPayeeText                              NSLocalizedString(@"Enter Payee", nil)
#define fromFormatString                            NSLocalizedString(@"From: %@", nil)
#define transactionDetailsHeaderText                NSLocalizedString(@"Transaction Details", @"Transaction Details header text")
#define airbitzEdgeLogin                            @"Airbitz Edge Login"
#define transactionDetailsHeaderText                NSLocalizedString(@"Transaction Details", @"Transaction Details header text")
#define loadingBalanceDotDotDot                     NSLocalizedString(@"Loading Balance...", @"title of wallets table balance header")
#define walletsTableHeaderText                      NSLocalizedString(@"WALLETS", @"title of active wallets table")
#define archiveTableHeaderText                      NSLocalizedString(@"ARCHIVE", @"title of archived wallets table")
#define resetDateText                               NSLocalizedString(@"Reset Date", nil)
#define resetRequestedText                          NSLocalizedString(@"Reset requested. Please retry login after 7 days.", nil)
#define creatingAndSecuringAccount                  NSLocalizedString(@"Creating and securing account", nil)
#define errorChangingPIN                            NSLocalizedString(@"Error Changing PIN", @"")
#define pinSuccessfullyChanged                      NSLocalizedString(@"PIN successfully changed.", @"")
#define disabledButtonText                          NSLocalizedString(@"Disabled", nil)
#define resetCancelledText                          NSLocalizedString(@"Reset Cancelled", nil)
#define unableToImportSecret                        NSLocalizedString(@"Unable to import secret", nil)
#define unableToDetermineTwoFactor                  NSLocalizedString(@"Unable to determine two factor status", nil)
#define twoFactorDisabled                           NSLocalizedString(@"Two Factor Disabled", nil)
#define requestConfirmedTwoFactorOff                NSLocalizedString(@"Request confirmed, Two Factor off.", nil)
#define createWalletText                            NSLocalizedString(@"Create Wallet", nil)
#define cameraUnavailablePleaseEnable               NSLocalizedString(@"Camera unavailable. Please enable camera access on your phone's Privacy Settings", @"")
#define successfullyLoggedIn                        NSLocalizedString(@"Successfully Logged In",nil)
#define errorLoggingIn                              NSLocalizedString(@"Error Logging In",nil)
#define invalidBluetoothRequest                     NSLocalizedString(@"Invalid Bluetooth Request", nil)
#define pleaseHaveRequestorContactSupport           NSLocalizedString(@"Please have Requestor contact support", nil)
#define importingFundsIntoWallet                    NSLocalizedString(@"Importing funds from %@ into wallet...", nil)
#define validatingAddressText                       NSLocalizedString(@"Validating Address...", nil)
#define importAgainToRetryTwitter                   NSLocalizedString(@"Import the private key again to retry Twitter", nil)
#define pinText                                     NSLocalizedString(@"PIN" ,nil)
#define usernameFormatString                        NSLocalizedString(@"User Name: %@" ,nil)
#define open24HoursText                             NSLocalizedString(@"Open 24 hours" ,nil)
#define open24Text                                  NSLocalizedString(@"Open 24" ,nil)
#define toFormatString                              NSLocalizedString(@"To: %@" ,nil)
#define walletCreateFailedFormatString              NSLocalizedString(@"Wallet creation failed:\n%@" ,nil)
#define unableToSaveSettings                        NSLocalizedString(@"Unable to save Settings", nil)
#define bitcoinDenominationText                     NSLocalizedString(@"Bitcoin", @"settings text")
#define mBitcoinDenominatinText                     NSLocalizedString(@"mBitcoin = (0.001 Bitcoin)", @"settings text")
#define bitsDenominationText                        NSLocalizedString(@"bits = (0.000001 Bitcoin)", @"settings text")
#define changeRecoveryQuestionsText                 NSLocalizedString(@"Change recovery questions", @"settings text")
#define changeCategoriesText                        NSLocalizedString(@"Change Categories", @"settings text")
#define spendingLimitsText                          NSLocalizedString(@"Spending Limits", @"spending limits text")
#define twoFactorSettingsHeader                     NSLocalizedString(@"2 Factor (Enhanced Security)", nil)
#define firstNameSettingsText                       NSLocalizedString(@"First Name (optional)", @"settings text")
#define lastNameSettingsText                        NSLocalizedString(@"Last Name (optional)", @"settings text")
#define nickNameSettingsText                        NSLocalizedString(@"Nickname / Handle (optional)", @"settings text")
#define sendNameOnPaymentText                       NSLocalizedString(@"Send name on payment request", @"settings text")
#define bluetoothText                               NSLocalizedString(@"Bluetooth", @"settings text")
#define enableBluetoothInSystem                     NSLocalizedString(@"Enable Bluetooth in System Settings", @"settings text")
#define merchangeModeText                           NSLocalizedString(@"Merchant Mode", @"settings text")
#define pinReloginText                              NSLocalizedString(@"PIN Re-Login", @"settings text")
#define touchIDUnsupportedText                      NSLocalizedString(@"TouchID: Unsupported Device", @"settings text")
#define touchIDSetPasswordFirst                     NSLocalizedString(@"TouchID: Set password first", @"settings text")
#define useTouchIDText                              NSLocalizedString(@"Use TouchID", @"settings text")
#define bitcoinDenominationHeader                   NSLocalizedString(@"BITCOIN DENOMINATION", @"section header in settings table")
#define accountInfoHeader                           NSLocalizedString(@"ACCOUNT: ", @"section header in settings table")
#define nameSettingsHeader                          NSLocalizedString(@"NAME", @"section header in settings table")
#define optionsSettingsHeader                       NSLocalizedString(@"OPTIONS", @"section header in settings table")
#define defaultExchangeRateHeader                   NSLocalizedString(@"DEFAULT EXCHANGE RATE", @"section header in settings table")
#define successfullyReceivedIdentityToken           NSLocalizedString(@"Successfully received identity token from %@" ,nil)
#define usa_and_canada_text                         NSLocalizedString(@"USA and Canada", nil)
#define usa_text                                    NSLocalizedString(@"USA", nil)
#define change_mining_fee_popup_title               NSLocalizedString(@"Change Mining Fee",nil)
#define change_mining_fee_popup_message             NSLocalizedString(@"Warning: Low Fees may cause long delays in transaction confirmation",nil)
#define affiliate_revenue                           NSLocalizedString(@"Affiliate Revenue", @"Income category for affiliate revenue")
#define change_mining_fee_low                       NSLocalizedString(@"Low Fee",nil)
#define change_mining_fee_standard                  NSLocalizedString(@"Standard Fee",nil)
#define change_mining_fee_high                      NSLocalizedString(@"High Fee",nil)
#define copied_text                                 NSLocalizedString(@"Copied",nil)

#define requestYourIdentityToken                    NSLocalizedString(@"Request your Identity Token. Please select one below" ,nil)
#define requestYourIdentityTokenButNone             NSLocalizedString(@"Request your Identity Token but you don't have any" ,nil)
#define requestPaymentAddress                       NSLocalizedString(@"Request a Payment Address" ,nil)
#define wouldLikeToColon                            NSLocalizedString(@"This site would like to:" ,nil)
#define provideIdentityTokenText                    NSLocalizedString(@"Provide an Identity Token" ,nil)
#define identity_token_created_and_saved            NSLocalizedString(@"Identity token from [%@] created and saved", nil)
#define create_new_text                             NSLocalizedString(@"Create new", nil)

#define second_text                                 NSLocalizedString(@"second",nil)
#define seconds_text                                NSLocalizedString(@"seconds",nil)
#define minute_text                                 NSLocalizedString(@"minute",nil)
#define minutes_text                                NSLocalizedString(@"minutes",nil)
#define hour_text                                   NSLocalizedString(@"hour",nil)
#define hours_text                                  NSLocalizedString(@"hours",nil)
#define day_text                                    NSLocalizedString(@"day",nil)
#define days_text                                   NSLocalizedString(@"days",nil)
#define default_currency_text                       NSLocalizedString(@"Default Currency", @"settings text")
#define default_exchange_text                       NSLocalizedString(@"Default Exchange", @"settings text")
#define exchange_rate_data_source_text              NSLocalizedString(@"Exchange Rate Data Source",nil)
#define income_category                             NSLocalizedString(@"Income",@"Prefix of list of income categories")
#define expense_category                            NSLocalizedString(@"Expense",@"Prefix of list of expense categories")
#define exchange_category                           NSLocalizedString(@"Exchange",@"Prefix of list of financial exchange categories. Such as converting from one currency to another")
#define transfer_category                           NSLocalizedString(@"Transfer",@"Financial transaction that moves money from one account to another")
#define income_category_en                          @"Income"
#define expense_category_en                         @"Expense"
#define exchange_category_en                        @"Exchange"
#define transfer_category_en                        @"Transfer"
#define wallet_category                             @"Wallet"

#define category_home_improvement                   NSLocalizedString(@"Home Improvement", @"expense category")
#define category_groceries                          NSLocalizedString(@"Groceries", @"expense category")
#define category_coffee_shops                       NSLocalizedString(@"Coffee Shops", @"expense category")
#define category_shopping                           NSLocalizedString(@"Shopping", @"expense category")
#define export_from_text                            NSLocalizedString(@"Export From:", @"Prompt asking which wallet to export from")
#define network_error_text                          NSLocalizedString(@"Network Error", @"")
#define messenger_server_error_funds_imported       NSLocalizedString(@"Funds successfully imported, but error connecting to messenger server. Try again later", @"")
#define error_creating_affiliate_link               NSLocalizedString(@"Error creating affiliate link. Please try again later", @"")
#define successfully_verified_identity              NSLocalizedString(@"Successfully Verified Identity",nil)
#define trouble_connecting_to_network               NSLocalizedString(@"Trouble connecting to network",nil)
#define error_connecting_to_payment_processor       NSLocalizedString(@"Error connecting to payment processor. Send directly to bitcoin address\n\n%@",nil)
#define show_qr_code                                NSLocalizedString(@"Show QR Code",nil)
#define disable_recovery_popup_title                NSLocalizedString(@"Disable Recovery?", @"Title of recovery popup")
#define disable_recovery_popup_message              NSLocalizedString(@"This account already has password recovery setup. Would you like to disable it?", @"Title of recovery popup message")
#define save_recovery_token_popup                   NSLocalizedString(@"Save Recovery Token", @"Title of recovery email popup")
#define save_recovery_token_popup_message           NSLocalizedString(@"To complete account recovery setup you MUST save an account recovery token. This will be required to recover your account in addition to your username and recovery answers. Please enter your email below to send yourself the recovery token.", @"Message of recovery token popup")
#define recovery_token_email_subject                NSLocalizedString(@"%@ Recovery Token", @"\'[Airbitz] Recovery Token\' Subject line of email to send recovery token for Airbitz or other whitelabelled wallet")
#define recovery_token_email_body                   NSLocalizedString(@"Please click the link below from a mobile device with %@ installed to initiate account recovery for username [%@]\n\n<br><br>%@", nil)
#define enter_username_to_recover                   NSLocalizedString(@"Please enter the username of the account to recover", nil)
#define recovery_not_setup                          NSLocalizedString(@"Recovery was not setup or was done on another device", nil)
#define recovery_not_setup2                         NSLocalizedString(@"If recovery was setup, you should have emailed yourself a recovery token with a link", nil)
#define recovery_not_setup3                         NSLocalizedString(@"Please find the email and click on the link from this device to initiate recovery", nil)
#define recovery_token_invalid                      NSLocalizedString(@"Incorrect username for this recovery token. Please try a different username or use a different recovery token link.", nil)
#define logout_before_recovery                      NSLocalizedString(@"Please logout of current account before attempting password recovery", nil)
#define recovery_successful                         NSLocalizedString(@"Recovery Successful\n\nPlease change your password and PIN", nil)
#define invalid_email                               NSLocalizedString(@"Invalid Email", nil)
#define buy_sell_bank_usa                           NSLocalizedString(@"Buy/Sell with Bank Account (USA)", nil)
#define fetching_login_request                      NSLocalizedString(@"Fetching Login Request...", @"Fetching Login Request popup")
#define approving_login_text                        NSLocalizedString(@"Approving Login...", @"Approving Login popup")



